plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'jp.jarvis.assistant'
    compileSdk 34

    defaultConfig {
        applicationId 'jp.jarvis.assistant'
        minSdk 23
        targetSdk 34
        versionCode 2
        versionName '0.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}
